API_KEY = "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"

[snowflake]
account = "account"   #"https://ooo.snowflakecomputing.com"のoooの部分
user = "nakamuranorito" #Snowflakeのユーザー名
password = "N@kamuran1"　#Snowflakeのパスワード
role = "role" #使用したいロール
warehouse = "compute_wh" #使用したいウェアハウス
database = "database" #使用したいデータがあるデータベース
schema = "schema" #同スキーマ
